// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order.proto

package orderpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListOrdersReq struct {
	ExchangeId           string   `protobuf:"bytes,1,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrdersReq) Reset()         { *m = ListOrdersReq{} }
func (m *ListOrdersReq) String() string { return proto.CompactTextString(m) }
func (*ListOrdersReq) ProtoMessage()    {}
func (*ListOrdersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65b0626cc3aada8, []int{0}
}

func (m *ListOrdersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrdersReq.Unmarshal(m, b)
}
func (m *ListOrdersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrdersReq.Marshal(b, m, deterministic)
}
func (m *ListOrdersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrdersReq.Merge(m, src)
}
func (m *ListOrdersReq) XXX_Size() int {
	return xxx_messageInfo_ListOrdersReq.Size(m)
}
func (m *ListOrdersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrdersReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrdersReq proto.InternalMessageInfo

func (m *ListOrdersReq) GetExchangeId() string {
	if m != nil {
		return m.ExchangeId
	}
	return ""
}

type ListOrdersRes struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrdersRes) Reset()         { *m = ListOrdersRes{} }
func (m *ListOrdersRes) String() string { return proto.CompactTextString(m) }
func (*ListOrdersRes) ProtoMessage()    {}
func (*ListOrdersRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65b0626cc3aada8, []int{1}
}

func (m *ListOrdersRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrdersRes.Unmarshal(m, b)
}
func (m *ListOrdersRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrdersRes.Marshal(b, m, deterministic)
}
func (m *ListOrdersRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrdersRes.Merge(m, src)
}
func (m *ListOrdersRes) XXX_Size() int {
	return xxx_messageInfo_ListOrdersRes.Size(m)
}
func (m *ListOrdersRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrdersRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrdersRes proto.InternalMessageInfo

func (m *ListOrdersRes) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type Order struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientOrderId        string   `protobuf:"bytes,2,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SubmittedAt          string   `protobuf:"bytes,5,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	FilledAt             string   `protobuf:"bytes,6,opt,name=filled_at,json=filledAt,proto3" json:"filled_at,omitempty"`
	ExpiredAt            string   `protobuf:"bytes,7,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	CanceledAt           string   `protobuf:"bytes,8,opt,name=canceled_at,json=canceledAt,proto3" json:"canceled_at,omitempty"`
	FailedAt             string   `protobuf:"bytes,9,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	ReplacedAt           string   `protobuf:"bytes,10,opt,name=replaced_at,json=replacedAt,proto3" json:"replaced_at,omitempty"`
	Replaces             string   `protobuf:"bytes,11,opt,name=replaces,proto3" json:"replaces,omitempty"`
	ReplacedBy           string   `protobuf:"bytes,12,opt,name=replaced_by,json=replacedBy,proto3" json:"replaced_by,omitempty"`
	AssetId              string   `protobuf:"bytes,13,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Symbol               string   `protobuf:"bytes,14,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange             string   `protobuf:"bytes,15,opt,name=exchange,proto3" json:"exchange,omitempty"`
	AssetClass           string   `protobuf:"bytes,16,opt,name=asset_class,json=assetClass,proto3" json:"asset_class,omitempty"`
	Qty                  float64  `protobuf:"fixed64,17,opt,name=qty,proto3" json:"qty,omitempty"`
	Notional             float64  `protobuf:"fixed64,18,opt,name=notional,proto3" json:"notional,omitempty"`
	FilledQty            float64  `protobuf:"fixed64,19,opt,name=filled_qty,json=filledQty,proto3" json:"filled_qty,omitempty"`
	OrderType            string   `protobuf:"bytes,20,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	Side                 string   `protobuf:"bytes,21,opt,name=side,proto3" json:"side,omitempty"`
	TimeInForce          string   `protobuf:"bytes,22,opt,name=time_in_force,json=timeInForce,proto3" json:"time_in_force,omitempty"`
	LimitPrice           float64  `protobuf:"fixed64,23,opt,name=limit_price,json=limitPrice,proto3" json:"limit_price,omitempty"`
	FilledAvgPrice       float64  `protobuf:"fixed64,24,opt,name=filled_avg_price,json=filledAvgPrice,proto3" json:"filled_avg_price,omitempty"`
	StopPrice            float64  `protobuf:"fixed64,25,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	TrailPrice           float64  `protobuf:"fixed64,26,opt,name=trail_price,json=trailPrice,proto3" json:"trail_price,omitempty"`
	TrailPercent         float64  `protobuf:"fixed64,27,opt,name=trail_percent,json=trailPercent,proto3" json:"trail_percent,omitempty"`
	Hwm                  float64  `protobuf:"fixed64,28,opt,name=hwm,proto3" json:"hwm,omitempty"`
	Status               string   `protobuf:"bytes,29,opt,name=status,proto3" json:"status,omitempty"`
	ExtendedHours        bool     `protobuf:"varint,30,opt,name=extended_hours,json=extendedHours,proto3" json:"extended_hours,omitempty"`
	Legs                 []*Order `protobuf:"bytes,31,rep,name=legs,proto3" json:"legs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65b0626cc3aada8, []int{2}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetClientOrderId() string {
	if m != nil {
		return m.ClientOrderId
	}
	return ""
}

func (m *Order) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Order) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Order) GetSubmittedAt() string {
	if m != nil {
		return m.SubmittedAt
	}
	return ""
}

func (m *Order) GetFilledAt() string {
	if m != nil {
		return m.FilledAt
	}
	return ""
}

func (m *Order) GetExpiredAt() string {
	if m != nil {
		return m.ExpiredAt
	}
	return ""
}

func (m *Order) GetCanceledAt() string {
	if m != nil {
		return m.CanceledAt
	}
	return ""
}

func (m *Order) GetFailedAt() string {
	if m != nil {
		return m.FailedAt
	}
	return ""
}

func (m *Order) GetReplacedAt() string {
	if m != nil {
		return m.ReplacedAt
	}
	return ""
}

func (m *Order) GetReplaces() string {
	if m != nil {
		return m.Replaces
	}
	return ""
}

func (m *Order) GetReplacedBy() string {
	if m != nil {
		return m.ReplacedBy
	}
	return ""
}

func (m *Order) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *Order) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Order) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Order) GetAssetClass() string {
	if m != nil {
		return m.AssetClass
	}
	return ""
}

func (m *Order) GetQty() float64 {
	if m != nil {
		return m.Qty
	}
	return 0
}

func (m *Order) GetNotional() float64 {
	if m != nil {
		return m.Notional
	}
	return 0
}

func (m *Order) GetFilledQty() float64 {
	if m != nil {
		return m.FilledQty
	}
	return 0
}

func (m *Order) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *Order) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *Order) GetTimeInForce() string {
	if m != nil {
		return m.TimeInForce
	}
	return ""
}

func (m *Order) GetLimitPrice() float64 {
	if m != nil {
		return m.LimitPrice
	}
	return 0
}

func (m *Order) GetFilledAvgPrice() float64 {
	if m != nil {
		return m.FilledAvgPrice
	}
	return 0
}

func (m *Order) GetStopPrice() float64 {
	if m != nil {
		return m.StopPrice
	}
	return 0
}

func (m *Order) GetTrailPrice() float64 {
	if m != nil {
		return m.TrailPrice
	}
	return 0
}

func (m *Order) GetTrailPercent() float64 {
	if m != nil {
		return m.TrailPercent
	}
	return 0
}

func (m *Order) GetHwm() float64 {
	if m != nil {
		return m.Hwm
	}
	return 0
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetExtendedHours() bool {
	if m != nil {
		return m.ExtendedHours
	}
	return false
}

func (m *Order) GetLegs() []*Order {
	if m != nil {
		return m.Legs
	}
	return nil
}

func init() {
	proto.RegisterType((*ListOrdersReq)(nil), "price.ListOrdersReq")
	proto.RegisterType((*ListOrdersRes)(nil), "price.ListOrdersRes")
	proto.RegisterType((*Order)(nil), "price.Order")
}

func init() {
	proto.RegisterFile("proto/order.proto", fileDescriptor_f65b0626cc3aada8)
}

var fileDescriptor_f65b0626cc3aada8 = []byte{
	// 600 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0x4f, 0x6f, 0xd3, 0x4c,
	0x10, 0xc6, 0x95, 0xb6, 0x69, 0x92, 0xc9, 0x9f, 0xb6, 0xfb, 0xf6, 0x2d, 0xdb, 0x96, 0xd2, 0x10,
	0x04, 0xca, 0xa9, 0x54, 0xed, 0x8d, 0x5b, 0x8a, 0x84, 0x08, 0x42, 0x02, 0x02, 0x27, 0x2e, 0x96,
	0x63, 0x4f, 0x93, 0x95, 0x1c, 0xdb, 0xdd, 0x9d, 0xb4, 0xf5, 0xa7, 0xe2, 0x2b, 0xa2, 0x9d, 0x59,
	0x17, 0x45, 0x70, 0xdb, 0xf9, 0x3d, 0xcf, 0xcc, 0xd8, 0x33, 0x6b, 0xc3, 0x41, 0x69, 0x0b, 0x2a,
	0xde, 0x16, 0x36, 0x45, 0x7b, 0xc1, 0x67, 0xd5, 0x2c, 0xad, 0x49, 0x70, 0x74, 0x09, 0xfd, 0xcf,
	0xc6, 0xd1, 0x17, 0xaf, 0xb8, 0x19, 0xde, 0xa9, 0x73, 0xe8, 0xe2, 0x63, 0xb2, 0x8c, 0xf3, 0x05,
	0x46, 0x26, 0xd5, 0x8d, 0x61, 0x63, 0xdc, 0x99, 0x41, 0x8d, 0xa6, 0xe9, 0xe8, 0x7a, 0x33, 0xc3,
	0xa9, 0x11, 0x34, 0xb9, 0x30, 0x7b, 0xbb, 0x57, 0xbd, 0x0b, 0xae, 0x7c, 0xc1, 0x86, 0x99, 0x48,
	0xa3, 0x5f, 0x2d, 0x68, 0x32, 0x50, 0x03, 0xd8, 0x7a, 0x2a, 0xbb, 0x65, 0x52, 0xf5, 0x06, 0xf6,
	0x92, 0xcc, 0x60, 0x4e, 0x11, 0x3b, 0x7d, 0xcf, 0x2d, 0x16, 0xfb, 0x82, 0x39, 0x6b, 0x9a, 0xaa,
	0x33, 0x80, 0xc4, 0x62, 0x4c, 0x98, 0x46, 0x31, 0xe9, 0x6d, 0xb6, 0x74, 0x02, 0x99, 0x90, 0x97,
	0xd7, 0x65, 0x5a, 0xcb, 0x3b, 0x22, 0x07, 0x32, 0x21, 0xf5, 0x12, 0x7a, 0x6e, 0x3d, 0x5f, 0x19,
	0x0a, 0x86, 0x26, 0x1b, 0xba, 0x4f, 0x6c, 0x42, 0xea, 0x14, 0x3a, 0xb7, 0x26, 0xcb, 0x44, 0xdf,
	0x65, 0xbd, 0x2d, 0x40, 0xca, 0xe3, 0x63, 0x69, 0xac, 0xa8, 0x2d, 0x29, 0x1f, 0xc8, 0x84, 0xfc,
	0xd0, 0x92, 0x38, 0x4f, 0x30, 0x64, 0xb7, 0x65, 0x68, 0x35, 0x0a, 0xc5, 0x63, 0x13, 0xe4, 0x4e,
	0x28, 0xce, 0x40, 0xb2, 0x2d, 0x96, 0x59, 0x9c, 0x88, 0x0c, 0x92, 0x5d, 0xa3, 0x09, 0xa9, 0x13,
	0x68, 0x87, 0xc8, 0xe9, 0xae, 0x24, 0xd7, 0xf1, 0x46, 0xf2, 0xbc, 0xd2, 0xbd, 0xcd, 0xe4, 0x9b,
	0x4a, 0x1d, 0x43, 0x3b, 0x76, 0x0e, 0xc9, 0x4f, 0xb6, 0xcf, 0x6a, 0x8b, 0xe3, 0x69, 0xaa, 0x8e,
	0x60, 0xd7, 0x55, 0xab, 0x79, 0x91, 0xe9, 0x01, 0x0b, 0x21, 0xf2, 0xfd, 0xea, 0x85, 0xeb, 0x3d,
	0xe9, 0x57, 0xc7, 0xbe, 0x9f, 0x94, 0x4b, 0xb2, 0xd8, 0x39, 0xbd, 0x2f, 0xfd, 0x18, 0xbd, 0xf7,
	0x44, 0xed, 0xc3, 0xf6, 0x1d, 0x55, 0xfa, 0x60, 0xd8, 0x18, 0x37, 0x66, 0xfe, 0xe8, 0xcb, 0xe5,
	0x05, 0x99, 0x22, 0x8f, 0x33, 0xad, 0x18, 0x3f, 0xc5, 0x7e, 0xb0, 0x61, 0xea, 0x3e, 0xe9, 0x3f,
	0x56, 0xc3, 0x1e, 0xbe, 0x51, 0xe5, 0x65, 0xb9, 0x16, 0x54, 0x95, 0xa8, 0x0f, 0x65, 0xee, 0x4c,
	0x7e, 0x54, 0x25, 0x2a, 0x05, 0x3b, 0xce, 0xa4, 0xa8, 0xff, 0x67, 0x81, 0xcf, 0x6a, 0x04, 0x7d,
	0x32, 0x2b, 0x8c, 0x4c, 0x1e, 0xdd, 0x16, 0x36, 0x41, 0x7d, 0x24, 0xbb, 0xf6, 0x70, 0x9a, 0x7f,
	0xf0, 0xc8, 0xbf, 0x44, 0x66, 0x56, 0x86, 0x22, 0xbe, 0xaa, 0xfa, 0x19, 0xb7, 0x05, 0x46, 0x5f,
	0x3d, 0x51, 0x63, 0xd8, 0xaf, 0x2f, 0xc3, 0xfd, 0x22, 0xb8, 0x34, 0xbb, 0x06, 0xe1, 0x4e, 0xdc,
	0x2f, 0xc4, 0x79, 0x06, 0xe0, 0xa8, 0x28, 0x83, 0xe7, 0x58, 0x5e, 0xc0, 0x13, 0x91, 0xcf, 0xa1,
	0x4b, 0x36, 0x36, 0x59, 0xd0, 0x4f, 0xa4, 0x13, 0x23, 0x31, 0xbc, 0x82, 0x7e, 0x30, 0xa0, 0x4d,
	0x30, 0x27, 0x7d, 0xca, 0x96, 0x9e, 0x58, 0x84, 0xf9, 0x99, 0x2e, 0x1f, 0x56, 0xfa, 0xb9, 0xcc,
	0x74, 0xf9, 0xb0, 0xe2, 0xd5, 0x51, 0x4c, 0x6b, 0xa7, 0xcf, 0xc2, 0xea, 0x38, 0x52, 0xaf, 0x61,
	0x80, 0x8f, 0x84, 0x79, 0x8a, 0x69, 0xb4, 0x2c, 0xd6, 0xd6, 0xe9, 0x17, 0xc3, 0xc6, 0xb8, 0x3d,
	0xeb, 0xd7, 0xf4, 0xa3, 0x87, 0x6a, 0x08, 0x3b, 0x19, 0x2e, 0x9c, 0x3e, 0x1f, 0x6e, 0xff, 0xf5,
	0xc9, 0xb2, 0x72, 0xf5, 0x09, 0x7a, 0x1c, 0x7e, 0x47, 0x7b, 0xef, 0x9f, 0xf3, 0x1d, 0xc0, 0x9f,
	0xcf, 0x5e, 0x1d, 0x86, 0x8c, 0x8d, 0x7f, 0xc7, 0xc9, 0xbf, 0xa8, 0xbb, 0x6c, 0xdc, 0x74, 0x7e,
	0xb6, 0x78, 0x67, 0xe5, 0x7c, 0xbe, 0xcb, 0x7f, 0x9f, 0xeb, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x8d, 0xe8, 0xe9, 0x24, 0x92, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (OrderService_ListOrdersClient, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (OrderService_ListOrdersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_OrderService_serviceDesc.Streams[0], "/price.OrderService/ListOrders", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderServiceListOrdersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OrderService_ListOrdersClient interface {
	Recv() (*ListOrdersRes, error)
	grpc.ClientStream
}

type orderServiceListOrdersClient struct {
	grpc.ClientStream
}

func (x *orderServiceListOrdersClient) Recv() (*ListOrdersRes, error) {
	m := new(ListOrdersRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	ListOrders(*ListOrdersReq, OrderService_ListOrdersServer) error
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) ListOrders(req *ListOrdersReq, srv OrderService_ListOrdersServer) error {
	return status.Errorf(codes.Unimplemented, "method ListOrders not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_ListOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListOrdersReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderServiceServer).ListOrders(m, &orderServiceListOrdersServer{stream})
}

type OrderService_ListOrdersServer interface {
	Send(*ListOrdersRes) error
	grpc.ServerStream
}

type orderServiceListOrdersServer struct {
	grpc.ServerStream
}

func (x *orderServiceListOrdersServer) Send(m *ListOrdersRes) error {
	return x.ServerStream.SendMsg(m)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "price.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListOrders",
			Handler:       _OrderService_ListOrders_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/order.proto",
}
