// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/price.proto

package pricepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListMyPositionReq struct {
	ExchangeId           string   `protobuf:"bytes,1,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMyPositionReq) Reset()         { *m = ListMyPositionReq{} }
func (m *ListMyPositionReq) String() string { return proto.CompactTextString(m) }
func (*ListMyPositionReq) ProtoMessage()    {}
func (*ListMyPositionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f96ae06f70243894, []int{0}
}

func (m *ListMyPositionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMyPositionReq.Unmarshal(m, b)
}
func (m *ListMyPositionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMyPositionReq.Marshal(b, m, deterministic)
}
func (m *ListMyPositionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMyPositionReq.Merge(m, src)
}
func (m *ListMyPositionReq) XXX_Size() int {
	return xxx_messageInfo_ListMyPositionReq.Size(m)
}
func (m *ListMyPositionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMyPositionReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListMyPositionReq proto.InternalMessageInfo

func (m *ListMyPositionReq) GetExchangeId() string {
	if m != nil {
		return m.ExchangeId
	}
	return ""
}

type ListMyPositionRes struct {
	Position             *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListMyPositionRes) Reset()         { *m = ListMyPositionRes{} }
func (m *ListMyPositionRes) String() string { return proto.CompactTextString(m) }
func (*ListMyPositionRes) ProtoMessage()    {}
func (*ListMyPositionRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_f96ae06f70243894, []int{1}
}

func (m *ListMyPositionRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMyPositionRes.Unmarshal(m, b)
}
func (m *ListMyPositionRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMyPositionRes.Marshal(b, m, deterministic)
}
func (m *ListMyPositionRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMyPositionRes.Merge(m, src)
}
func (m *ListMyPositionRes) XXX_Size() int {
	return xxx_messageInfo_ListMyPositionRes.Size(m)
}
func (m *ListMyPositionRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMyPositionRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListMyPositionRes proto.InternalMessageInfo

func (m *ListMyPositionRes) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

type Position struct {
	AssetId              string   `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange             string   `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	AssetClass           string   `protobuf:"bytes,4,opt,name=asset_class,json=assetClass,proto3" json:"asset_class,omitempty"`
	AccountId            string   `protobuf:"bytes,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AvgEntryPrice        float64  `protobuf:"fixed64,6,opt,name=avg_entry_price,json=avgEntryPrice,proto3" json:"avg_entry_price,omitempty"`
	Qty                  float64  `protobuf:"fixed64,7,opt,name=qty,proto3" json:"qty,omitempty"`
	Side                 string   `protobuf:"bytes,8,opt,name=side,proto3" json:"side,omitempty"`
	MarketValue          float64  `protobuf:"fixed64,9,opt,name=market_value,json=marketValue,proto3" json:"market_value,omitempty"`
	CostBasis            float64  `protobuf:"fixed64,10,opt,name=cost_basis,json=costBasis,proto3" json:"cost_basis,omitempty"`
	UnrealizedPl         float64  `protobuf:"fixed64,11,opt,name=unrealized_pl,json=unrealizedPl,proto3" json:"unrealized_pl,omitempty"`
	UnrealizedPlpc       float64  `protobuf:"fixed64,12,opt,name=unrealized_plpc,json=unrealizedPlpc,proto3" json:"unrealized_plpc,omitempty"`
	CurrentPrice         float64  `protobuf:"fixed64,13,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	LastdayPrice         float64  `protobuf:"fixed64,14,opt,name=lastday_price,json=lastdayPrice,proto3" json:"lastday_price,omitempty"`
	ChangeToday          float64  `protobuf:"fixed64,15,opt,name=change_today,json=changeToday,proto3" json:"change_today,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_f96ae06f70243894, []int{2}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *Position) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Position) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Position) GetAssetClass() string {
	if m != nil {
		return m.AssetClass
	}
	return ""
}

func (m *Position) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Position) GetAvgEntryPrice() float64 {
	if m != nil {
		return m.AvgEntryPrice
	}
	return 0
}

func (m *Position) GetQty() float64 {
	if m != nil {
		return m.Qty
	}
	return 0
}

func (m *Position) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *Position) GetMarketValue() float64 {
	if m != nil {
		return m.MarketValue
	}
	return 0
}

func (m *Position) GetCostBasis() float64 {
	if m != nil {
		return m.CostBasis
	}
	return 0
}

func (m *Position) GetUnrealizedPl() float64 {
	if m != nil {
		return m.UnrealizedPl
	}
	return 0
}

func (m *Position) GetUnrealizedPlpc() float64 {
	if m != nil {
		return m.UnrealizedPlpc
	}
	return 0
}

func (m *Position) GetCurrentPrice() float64 {
	if m != nil {
		return m.CurrentPrice
	}
	return 0
}

func (m *Position) GetLastdayPrice() float64 {
	if m != nil {
		return m.LastdayPrice
	}
	return 0
}

func (m *Position) GetChangeToday() float64 {
	if m != nil {
		return m.ChangeToday
	}
	return 0
}

func init() {
	proto.RegisterType((*ListMyPositionReq)(nil), "price.ListMyPositionReq")
	proto.RegisterType((*ListMyPositionRes)(nil), "price.ListMyPositionRes")
	proto.RegisterType((*Position)(nil), "price.Position")
}

func init() {
	proto.RegisterFile("proto/price.proto", fileDescriptor_f96ae06f70243894)
}

var fileDescriptor_f96ae06f70243894 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xdf, 0x6a, 0x14, 0x31,
	0x14, 0xc6, 0x19, 0xb7, 0xdd, 0x9d, 0x39, 0x3b, 0xdb, 0xb1, 0xb9, 0x90, 0x58, 0x10, 0xdb, 0x2d,
	0x68, 0x41, 0xa8, 0x52, 0x7d, 0x00, 0xa9, 0x88, 0x2c, 0x28, 0x2c, 0xab, 0x28, 0x78, 0x33, 0x64,
	0x92, 0xb0, 0x06, 0xa7, 0x93, 0x69, 0x92, 0x19, 0x1c, 0x9f, 0xd7, 0x07, 0x91, 0x9c, 0x64, 0xb6,
	0x96, 0xc5, 0xbb, 0x9c, 0xdf, 0xf7, 0x9d, 0x7f, 0xe1, 0xc0, 0x71, 0x6b, 0xb4, 0xd3, 0x2f, 0x5b,
	0xa3, 0xb8, 0xbc, 0xc4, 0x37, 0x39, 0xc4, 0x60, 0xf9, 0x06, 0x8e, 0x3f, 0x2a, 0xeb, 0x3e, 0x0d,
	0x6b, 0x6d, 0x95, 0x53, 0xba, 0xd9, 0xc8, 0x5b, 0xf2, 0x14, 0xe6, 0xf2, 0x17, 0xff, 0xc1, 0x9a,
	0xad, 0x2c, 0x95, 0xa0, 0xc9, 0x69, 0x72, 0x91, 0x6d, 0x60, 0x44, 0x2b, 0xb1, 0x7c, 0xbb, 0x9f,
	0x65, 0xc9, 0x0b, 0x48, 0xdb, 0x18, 0x62, 0xca, 0xfc, 0xaa, 0xb8, 0x0c, 0x1d, 0x77, 0xae, 0x9d,
	0x61, 0xf9, 0x67, 0x02, 0xe9, 0x88, 0xc9, 0x63, 0x48, 0x99, 0xb5, 0xd2, 0xdd, 0x35, 0x9b, 0x61,
	0xbc, 0x12, 0xe4, 0x11, 0x4c, 0xed, 0x70, 0x53, 0xe9, 0x9a, 0x3e, 0x40, 0x21, 0x46, 0xe4, 0x04,
	0xd2, 0x71, 0x1e, 0x3a, 0x41, 0x65, 0x17, 0xfb, 0xf1, 0x43, 0x39, 0x5e, 0x33, 0x6b, 0xe9, 0x41,
	0x18, 0x1f, 0xd1, 0x3b, 0x4f, 0xc8, 0x13, 0x00, 0xc6, 0xb9, 0xee, 0x1a, 0xec, 0x78, 0x88, 0x7a,
	0x16, 0xc9, 0x4a, 0x90, 0x67, 0x50, 0xb0, 0x7e, 0x5b, 0xca, 0xc6, 0x99, 0xa1, 0xc4, 0x0d, 0xe8,
	0xf4, 0x34, 0xb9, 0x48, 0x36, 0x0b, 0xd6, 0x6f, 0xdf, 0x7b, 0xba, 0xf6, 0x90, 0x3c, 0x84, 0xc9,
	0xad, 0x1b, 0xe8, 0x0c, 0x35, 0xff, 0x24, 0x04, 0x0e, 0xac, 0x12, 0x92, 0xa6, 0x58, 0x12, 0xdf,
	0xe4, 0x0c, 0xf2, 0x1b, 0x66, 0x7e, 0x4a, 0x57, 0xf6, 0xac, 0xee, 0x24, 0xcd, 0xd0, 0x3e, 0x0f,
	0xec, 0xab, 0x47, 0x7e, 0x1e, 0xae, 0xad, 0x2b, 0x2b, 0x66, 0x95, 0xa5, 0x80, 0x86, 0xcc, 0x93,
	0x6b, 0x0f, 0xc8, 0x39, 0x2c, 0xba, 0xc6, 0x48, 0x56, 0xab, 0xdf, 0x52, 0x94, 0x6d, 0x4d, 0xe7,
	0xe8, 0xc8, 0xef, 0xe0, 0xba, 0x26, 0xcf, 0xa1, 0xb8, 0x67, 0x6a, 0x39, 0xcd, 0xd1, 0x76, 0xf4,
	0xaf, 0xad, 0xe5, 0xbe, 0x1a, 0xef, 0x8c, 0x91, 0x8d, 0x8b, 0xbb, 0x2d, 0x42, 0xb5, 0x08, 0xc3,
	0x6a, 0xe7, 0xb0, 0xa8, 0x99, 0x75, 0x82, 0x8d, 0x1f, 0x70, 0x14, 0x4c, 0x11, 0x06, 0xd3, 0x19,
	0xe4, 0xf1, 0x48, 0x9c, 0x16, 0x6c, 0xa0, 0x45, 0xd8, 0x2c, 0xb0, 0x2f, 0x1e, 0x5d, 0x7d, 0x83,
	0x1c, 0xbd, 0x9f, 0xa5, 0xe9, 0x7d, 0xca, 0x07, 0x28, 0xee, 0x1f, 0x8e, 0x25, 0x34, 0x1e, 0xc9,
	0xde, 0x19, 0x9e, 0xfc, 0x4f, 0xb1, 0xaf, 0x92, 0xeb, 0xec, 0xfb, 0x0c, 0xc5, 0xb6, 0xaa, 0xa6,
	0x78, 0xd0, 0xaf, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x6a, 0xbb, 0xe3, 0x35, 0xe5, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PriceServiceClient is the client API for PriceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PriceServiceClient interface {
	ListMyPositions(ctx context.Context, in *ListMyPositionReq, opts ...grpc.CallOption) (PriceService_ListMyPositionsClient, error)
}

type priceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPriceServiceClient(cc grpc.ClientConnInterface) PriceServiceClient {
	return &priceServiceClient{cc}
}

func (c *priceServiceClient) ListMyPositions(ctx context.Context, in *ListMyPositionReq, opts ...grpc.CallOption) (PriceService_ListMyPositionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PriceService_serviceDesc.Streams[0], "/price.PriceService/ListMyPositions", opts...)
	if err != nil {
		return nil, err
	}
	x := &priceServiceListMyPositionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PriceService_ListMyPositionsClient interface {
	Recv() (*ListMyPositionRes, error)
	grpc.ClientStream
}

type priceServiceListMyPositionsClient struct {
	grpc.ClientStream
}

func (x *priceServiceListMyPositionsClient) Recv() (*ListMyPositionRes, error) {
	m := new(ListMyPositionRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PriceServiceServer is the server API for PriceService service.
type PriceServiceServer interface {
	ListMyPositions(*ListMyPositionReq, PriceService_ListMyPositionsServer) error
}

// UnimplementedPriceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPriceServiceServer struct {
}

func (*UnimplementedPriceServiceServer) ListMyPositions(req *ListMyPositionReq, srv PriceService_ListMyPositionsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListMyPositions not implemented")
}

func RegisterPriceServiceServer(s *grpc.Server, srv PriceServiceServer) {
	s.RegisterService(&_PriceService_serviceDesc, srv)
}

func _PriceService_ListMyPositions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListMyPositionReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PriceServiceServer).ListMyPositions(m, &priceServiceListMyPositionsServer{stream})
}

type PriceService_ListMyPositionsServer interface {
	Send(*ListMyPositionRes) error
	grpc.ServerStream
}

type priceServiceListMyPositionsServer struct {
	grpc.ServerStream
}

func (x *priceServiceListMyPositionsServer) Send(m *ListMyPositionRes) error {
	return x.ServerStream.SendMsg(m)
}

var _PriceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "price.PriceService",
	HandlerType: (*PriceServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListMyPositions",
			Handler:       _PriceService_ListMyPositions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/price.proto",
}
