---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-service-app
  namespace: hedgina
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange-service
  template:
    metadata:
      labels:
        app: exchange-service
    spec:
      containers:
      - name: exchange-service
        image: neha190495/exchange-service:latest
        imagePullPolicy: IfNotPresent
        resources: {}
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: exchange-service
  namespace: hedgina
spec:
  type: LoadBalancer
  ports:
  - name: tcp
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: exchange-service
---
apiVersion: v1
kind: Service
metadata:
  name: exchange-service-clusterip
  namespace: hedgina
spec:
  type: ClusterIP
  ports:
  - name: tcp
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: exchange-service