// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/strategy.proto

package strategypb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Strategy_Status int32

const (
	Strategy_STOPPED Strategy_Status = 0
	Strategy_STARTED Strategy_Status = 1
)

var Strategy_Status_name = map[int32]string{
	0: "STOPPED",
	1: "STARTED",
}

var Strategy_Status_value = map[string]int32{
	"STOPPED": 0,
	"STARTED": 1,
}

func (x Strategy_Status) String() string {
	return proto.EnumName(Strategy_Status_name, int32(x))
}

func (Strategy_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a9cfd4cb1c623bb, []int{0, 0}
}

type Strategy struct {
	Id                      string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StrategyName            string          `protobuf:"bytes,2,opt,name=strategy_name,json=strategyName,proto3" json:"strategy_name,omitempty"`
	SelectedExchange        string          `protobuf:"bytes,3,opt,name=selected_exchange,json=selectedExchange,proto3" json:"selected_exchange,omitempty"`
	StrategyType            string          `protobuf:"bytes,4,opt,name=strategy_type,json=strategyType,proto3" json:"strategy_type,omitempty"`
	StartOrderType          string          `protobuf:"bytes,5,opt,name=start_order_type,json=startOrderType,proto3" json:"start_order_type,omitempty"`
	DealStartCondition      string          `protobuf:"bytes,6,opt,name=deal_start_condition,json=dealStartCondition,proto3" json:"deal_start_condition,omitempty"`
	BaseOrderSize           float64         `protobuf:"fixed64,7,opt,name=base_order_size,json=baseOrderSize,proto3" json:"base_order_size,omitempty"`
	SafetyOrderSize         float64         `protobuf:"fixed64,8,opt,name=safety_order_size,json=safetyOrderSize,proto3" json:"safety_order_size,omitempty"`
	MaxSafetyTradeAcc       string          `protobuf:"bytes,9,opt,name=max_safety_trade_acc,json=maxSafetyTradeAcc,proto3" json:"max_safety_trade_acc,omitempty"`
	PriceDevation           string          `protobuf:"bytes,10,opt,name=price_devation,json=priceDevation,proto3" json:"price_devation,omitempty"`
	SafetyOrderVolumeScale  string          `protobuf:"bytes,11,opt,name=safety_order_volume_scale,json=safetyOrderVolumeScale,proto3" json:"safety_order_volume_scale,omitempty"`
	SafetyOrderStepScale    string          `protobuf:"bytes,12,opt,name=safety_order_step_scale,json=safetyOrderStepScale,proto3" json:"safety_order_step_scale,omitempty"`
	TakeProfit              string          `protobuf:"bytes,13,opt,name=take_profit,json=takeProfit,proto3" json:"take_profit,omitempty"`
	TargetProfit            string          `protobuf:"bytes,14,opt,name=target_profit,json=targetProfit,proto3" json:"target_profit,omitempty"`
	AllocateFundsToStrategy string          `protobuf:"bytes,15,opt,name=allocate_funds_to_strategy,json=allocateFundsToStrategy,proto3" json:"allocate_funds_to_strategy,omitempty"`
	UserId                  string          `protobuf:"bytes,16,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Version                 int64           `protobuf:"varint,17,opt,name=version,proto3" json:"version,omitempty"`
	Status                  Strategy_Status `protobuf:"varint,18,opt,name=status,proto3,enum=strategy.Strategy_Status" json:"status,omitempty"`
	Stock                   []*Stock        `protobuf:"bytes,19,rep,name=stock,proto3" json:"stock,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}        `json:"-"`
	XXX_unrecognized        []byte          `json:"-"`
	XXX_sizecache           int32           `json:"-"`
}

func (m *Strategy) Reset()         { *m = Strategy{} }
func (m *Strategy) String() string { return proto.CompactTextString(m) }
func (*Strategy) ProtoMessage()    {}
func (*Strategy) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a9cfd4cb1c623bb, []int{0}
}

func (m *Strategy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Strategy.Unmarshal(m, b)
}
func (m *Strategy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Strategy.Marshal(b, m, deterministic)
}
func (m *Strategy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Strategy.Merge(m, src)
}
func (m *Strategy) XXX_Size() int {
	return xxx_messageInfo_Strategy.Size(m)
}
func (m *Strategy) XXX_DiscardUnknown() {
	xxx_messageInfo_Strategy.DiscardUnknown(m)
}

var xxx_messageInfo_Strategy proto.InternalMessageInfo

func (m *Strategy) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Strategy) GetStrategyName() string {
	if m != nil {
		return m.StrategyName
	}
	return ""
}

func (m *Strategy) GetSelectedExchange() string {
	if m != nil {
		return m.SelectedExchange
	}
	return ""
}

func (m *Strategy) GetStrategyType() string {
	if m != nil {
		return m.StrategyType
	}
	return ""
}

func (m *Strategy) GetStartOrderType() string {
	if m != nil {
		return m.StartOrderType
	}
	return ""
}

func (m *Strategy) GetDealStartCondition() string {
	if m != nil {
		return m.DealStartCondition
	}
	return ""
}

func (m *Strategy) GetBaseOrderSize() float64 {
	if m != nil {
		return m.BaseOrderSize
	}
	return 0
}

func (m *Strategy) GetSafetyOrderSize() float64 {
	if m != nil {
		return m.SafetyOrderSize
	}
	return 0
}

func (m *Strategy) GetMaxSafetyTradeAcc() string {
	if m != nil {
		return m.MaxSafetyTradeAcc
	}
	return ""
}

func (m *Strategy) GetPriceDevation() string {
	if m != nil {
		return m.PriceDevation
	}
	return ""
}

func (m *Strategy) GetSafetyOrderVolumeScale() string {
	if m != nil {
		return m.SafetyOrderVolumeScale
	}
	return ""
}

func (m *Strategy) GetSafetyOrderStepScale() string {
	if m != nil {
		return m.SafetyOrderStepScale
	}
	return ""
}

func (m *Strategy) GetTakeProfit() string {
	if m != nil {
		return m.TakeProfit
	}
	return ""
}

func (m *Strategy) GetTargetProfit() string {
	if m != nil {
		return m.TargetProfit
	}
	return ""
}

func (m *Strategy) GetAllocateFundsToStrategy() string {
	if m != nil {
		return m.AllocateFundsToStrategy
	}
	return ""
}

func (m *Strategy) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Strategy) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Strategy) GetStatus() Strategy_Status {
	if m != nil {
		return m.Status
	}
	return Strategy_STOPPED
}

func (m *Strategy) GetStock() []*Stock {
	if m != nil {
		return m.Stock
	}
	return nil
}

type Stock struct {
	StockName            string   `protobuf:"bytes,1,opt,name=stock_name,json=stockName,proto3" json:"stock_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stock) Reset()         { *m = Stock{} }
func (m *Stock) String() string { return proto.CompactTextString(m) }
func (*Stock) ProtoMessage()    {}
func (*Stock) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a9cfd4cb1c623bb, []int{1}
}

func (m *Stock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stock.Unmarshal(m, b)
}
func (m *Stock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stock.Marshal(b, m, deterministic)
}
func (m *Stock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stock.Merge(m, src)
}
func (m *Stock) XXX_Size() int {
	return xxx_messageInfo_Stock.Size(m)
}
func (m *Stock) XXX_DiscardUnknown() {
	xxx_messageInfo_Stock.DiscardUnknown(m)
}

var xxx_messageInfo_Stock proto.InternalMessageInfo

func (m *Stock) GetStockName() string {
	if m != nil {
		return m.StockName
	}
	return ""
}

type CreateStrategyReq struct {
	Strategy             *Strategy `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateStrategyReq) Reset()         { *m = CreateStrategyReq{} }
func (m *CreateStrategyReq) String() string { return proto.CompactTextString(m) }
func (*CreateStrategyReq) ProtoMessage()    {}
func (*CreateStrategyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a9cfd4cb1c623bb, []int{2}
}

func (m *CreateStrategyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStrategyReq.Unmarshal(m, b)
}
func (m *CreateStrategyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStrategyReq.Marshal(b, m, deterministic)
}
func (m *CreateStrategyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStrategyReq.Merge(m, src)
}
func (m *CreateStrategyReq) XXX_Size() int {
	return xxx_messageInfo_CreateStrategyReq.Size(m)
}
func (m *CreateStrategyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStrategyReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStrategyReq proto.InternalMessageInfo

func (m *CreateStrategyReq) GetStrategy() *Strategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

type CreateStrategyRes struct {
	Strategy             *Strategy `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateStrategyRes) Reset()         { *m = CreateStrategyRes{} }
func (m *CreateStrategyRes) String() string { return proto.CompactTextString(m) }
func (*CreateStrategyRes) ProtoMessage()    {}
func (*CreateStrategyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a9cfd4cb1c623bb, []int{3}
}

func (m *CreateStrategyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStrategyRes.Unmarshal(m, b)
}
func (m *CreateStrategyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStrategyRes.Marshal(b, m, deterministic)
}
func (m *CreateStrategyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStrategyRes.Merge(m, src)
}
func (m *CreateStrategyRes) XXX_Size() int {
	return xxx_messageInfo_CreateStrategyRes.Size(m)
}
func (m *CreateStrategyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStrategyRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStrategyRes proto.InternalMessageInfo

func (m *CreateStrategyRes) GetStrategy() *Strategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

type UpdateStrategyReq struct {
	Strategy             *Strategy `protobuf:"bytes,1,opt,name=Strategy,proto3" json:"Strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateStrategyReq) Reset()         { *m = UpdateStrategyReq{} }
func (m *UpdateStrategyReq) String() string { return proto.CompactTextString(m) }
func (*UpdateStrategyReq) ProtoMessage()    {}
func (*UpdateStrategyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a9cfd4cb1c623bb, []int{4}
}

func (m *UpdateStrategyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStrategyReq.Unmarshal(m, b)
}
func (m *UpdateStrategyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStrategyReq.Marshal(b, m, deterministic)
}
func (m *UpdateStrategyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStrategyReq.Merge(m, src)
}
func (m *UpdateStrategyReq) XXX_Size() int {
	return xxx_messageInfo_UpdateStrategyReq.Size(m)
}
func (m *UpdateStrategyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStrategyReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStrategyReq proto.InternalMessageInfo

func (m *UpdateStrategyReq) GetStrategy() *Strategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

type UpdateStrategyRes struct {
	Strategy             *Strategy `protobuf:"bytes,1,opt,name=Strategy,proto3" json:"Strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateStrategyRes) Reset()         { *m = UpdateStrategyRes{} }
func (m *UpdateStrategyRes) String() string { return proto.CompactTextString(m) }
func (*UpdateStrategyRes) ProtoMessage()    {}
func (*UpdateStrategyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a9cfd4cb1c623bb, []int{5}
}

func (m *UpdateStrategyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStrategyRes.Unmarshal(m, b)
}
func (m *UpdateStrategyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStrategyRes.Marshal(b, m, deterministic)
}
func (m *UpdateStrategyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStrategyRes.Merge(m, src)
}
func (m *UpdateStrategyRes) XXX_Size() int {
	return xxx_messageInfo_UpdateStrategyRes.Size(m)
}
func (m *UpdateStrategyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStrategyRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStrategyRes proto.InternalMessageInfo

func (m *UpdateStrategyRes) GetStrategy() *Strategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

type ReadStrategyReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadStrategyReq) Reset()         { *m = ReadStrategyReq{} }
func (m *ReadStrategyReq) String() string { return proto.CompactTextString(m) }
func (*ReadStrategyReq) ProtoMessage()    {}
func (*ReadStrategyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a9cfd4cb1c623bb, []int{6}
}

func (m *ReadStrategyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadStrategyReq.Unmarshal(m, b)
}
func (m *ReadStrategyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadStrategyReq.Marshal(b, m, deterministic)
}
func (m *ReadStrategyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadStrategyReq.Merge(m, src)
}
func (m *ReadStrategyReq) XXX_Size() int {
	return xxx_messageInfo_ReadStrategyReq.Size(m)
}
func (m *ReadStrategyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadStrategyReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadStrategyReq proto.InternalMessageInfo

func (m *ReadStrategyReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadStrategyRes struct {
	Strategy             *Strategy `protobuf:"bytes,1,opt,name=Strategy,proto3" json:"Strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReadStrategyRes) Reset()         { *m = ReadStrategyRes{} }
func (m *ReadStrategyRes) String() string { return proto.CompactTextString(m) }
func (*ReadStrategyRes) ProtoMessage()    {}
func (*ReadStrategyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a9cfd4cb1c623bb, []int{7}
}

func (m *ReadStrategyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadStrategyRes.Unmarshal(m, b)
}
func (m *ReadStrategyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadStrategyRes.Marshal(b, m, deterministic)
}
func (m *ReadStrategyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadStrategyRes.Merge(m, src)
}
func (m *ReadStrategyRes) XXX_Size() int {
	return xxx_messageInfo_ReadStrategyRes.Size(m)
}
func (m *ReadStrategyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadStrategyRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadStrategyRes proto.InternalMessageInfo

func (m *ReadStrategyRes) GetStrategy() *Strategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

type DeleteStrategyReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStrategyReq) Reset()         { *m = DeleteStrategyReq{} }
func (m *DeleteStrategyReq) String() string { return proto.CompactTextString(m) }
func (*DeleteStrategyReq) ProtoMessage()    {}
func (*DeleteStrategyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a9cfd4cb1c623bb, []int{8}
}

func (m *DeleteStrategyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStrategyReq.Unmarshal(m, b)
}
func (m *DeleteStrategyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStrategyReq.Marshal(b, m, deterministic)
}
func (m *DeleteStrategyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStrategyReq.Merge(m, src)
}
func (m *DeleteStrategyReq) XXX_Size() int {
	return xxx_messageInfo_DeleteStrategyReq.Size(m)
}
func (m *DeleteStrategyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStrategyReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStrategyReq proto.InternalMessageInfo

func (m *DeleteStrategyReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteStrategyRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStrategyRes) Reset()         { *m = DeleteStrategyRes{} }
func (m *DeleteStrategyRes) String() string { return proto.CompactTextString(m) }
func (*DeleteStrategyRes) ProtoMessage()    {}
func (*DeleteStrategyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a9cfd4cb1c623bb, []int{9}
}

func (m *DeleteStrategyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStrategyRes.Unmarshal(m, b)
}
func (m *DeleteStrategyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStrategyRes.Marshal(b, m, deterministic)
}
func (m *DeleteStrategyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStrategyRes.Merge(m, src)
}
func (m *DeleteStrategyRes) XXX_Size() int {
	return xxx_messageInfo_DeleteStrategyRes.Size(m)
}
func (m *DeleteStrategyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStrategyRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStrategyRes proto.InternalMessageInfo

func (m *DeleteStrategyRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ListStrategyReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStrategyReq) Reset()         { *m = ListStrategyReq{} }
func (m *ListStrategyReq) String() string { return proto.CompactTextString(m) }
func (*ListStrategyReq) ProtoMessage()    {}
func (*ListStrategyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a9cfd4cb1c623bb, []int{10}
}

func (m *ListStrategyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStrategyReq.Unmarshal(m, b)
}
func (m *ListStrategyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStrategyReq.Marshal(b, m, deterministic)
}
func (m *ListStrategyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStrategyReq.Merge(m, src)
}
func (m *ListStrategyReq) XXX_Size() int {
	return xxx_messageInfo_ListStrategyReq.Size(m)
}
func (m *ListStrategyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStrategyReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListStrategyReq proto.InternalMessageInfo

func (m *ListStrategyReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ListStrategyRes struct {
	Strategy             *Strategy `protobuf:"bytes,1,opt,name=Strategy,proto3" json:"Strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListStrategyRes) Reset()         { *m = ListStrategyRes{} }
func (m *ListStrategyRes) String() string { return proto.CompactTextString(m) }
func (*ListStrategyRes) ProtoMessage()    {}
func (*ListStrategyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a9cfd4cb1c623bb, []int{11}
}

func (m *ListStrategyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStrategyRes.Unmarshal(m, b)
}
func (m *ListStrategyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStrategyRes.Marshal(b, m, deterministic)
}
func (m *ListStrategyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStrategyRes.Merge(m, src)
}
func (m *ListStrategyRes) XXX_Size() int {
	return xxx_messageInfo_ListStrategyRes.Size(m)
}
func (m *ListStrategyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStrategyRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListStrategyRes proto.InternalMessageInfo

func (m *ListStrategyRes) GetStrategy() *Strategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

func init() {
	proto.RegisterEnum("strategy.Strategy_Status", Strategy_Status_name, Strategy_Status_value)
	proto.RegisterType((*Strategy)(nil), "strategy.Strategy")
	proto.RegisterType((*Stock)(nil), "strategy.Stock")
	proto.RegisterType((*CreateStrategyReq)(nil), "strategy.CreateStrategyReq")
	proto.RegisterType((*CreateStrategyRes)(nil), "strategy.CreateStrategyRes")
	proto.RegisterType((*UpdateStrategyReq)(nil), "strategy.UpdateStrategyReq")
	proto.RegisterType((*UpdateStrategyRes)(nil), "strategy.UpdateStrategyRes")
	proto.RegisterType((*ReadStrategyReq)(nil), "strategy.ReadStrategyReq")
	proto.RegisterType((*ReadStrategyRes)(nil), "strategy.ReadStrategyRes")
	proto.RegisterType((*DeleteStrategyReq)(nil), "strategy.DeleteStrategyReq")
	proto.RegisterType((*DeleteStrategyRes)(nil), "strategy.DeleteStrategyRes")
	proto.RegisterType((*ListStrategyReq)(nil), "strategy.ListStrategyReq")
	proto.RegisterType((*ListStrategyRes)(nil), "strategy.ListStrategyRes")
}

func init() {
	proto.RegisterFile("proto/strategy.proto", fileDescriptor_8a9cfd4cb1c623bb)
}

var fileDescriptor_8a9cfd4cb1c623bb = []byte{
	// 671 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x95, 0x5f, 0x4f, 0xdb, 0x4a,
	0x10, 0xc5, 0xaf, 0xe1, 0x92, 0x84, 0x09, 0xf9, 0xb7, 0x37, 0xba, 0x2c, 0x5c, 0x5d, 0x35, 0x35,
	0x02, 0x45, 0x54, 0x85, 0x36, 0x55, 0x1f, 0xaa, 0x3e, 0x51, 0x42, 0xa5, 0x56, 0x55, 0x41, 0x76,
	0xda, 0x87, 0x4a, 0x95, 0xb5, 0xac, 0x07, 0x6a, 0xe1, 0xc4, 0xae, 0x77, 0x13, 0x11, 0xbe, 0x5c,
	0xbf, 0x5a, 0xb5, 0x63, 0x9b, 0xd8, 0xa4, 0x42, 0xa5, 0x6f, 0x9e, 0x73, 0x7e, 0x73, 0x3c, 0x8b,
	0x67, 0x09, 0x74, 0xe3, 0x24, 0xd2, 0xd1, 0xa1, 0xd2, 0x89, 0xd0, 0x78, 0x39, 0x3f, 0xa0, 0x92,
	0xd5, 0xf2, 0xda, 0xfe, 0x51, 0x81, 0x9a, 0x9b, 0x15, 0xac, 0x09, 0x2b, 0x81, 0xcf, 0xad, 0x9e,
	0xd5, 0x5f, 0x77, 0x56, 0x02, 0x9f, 0xed, 0x40, 0x23, 0x07, 0xbd, 0x89, 0x18, 0x23, 0x5f, 0x21,
	0x6b, 0x23, 0x17, 0x3f, 0x8a, 0x31, 0xb2, 0x27, 0xd0, 0x51, 0x18, 0xa2, 0xd4, 0xe8, 0x7b, 0x78,
	0x2d, 0xbf, 0x89, 0xc9, 0x25, 0xf2, 0x55, 0x02, 0xdb, 0xb9, 0x71, 0x92, 0xe9, 0xa5, 0x44, 0x3d,
	0x8f, 0x91, 0xff, 0x5d, 0x4e, 0x1c, 0xcd, 0x63, 0x64, 0x7d, 0x68, 0x2b, 0x2d, 0x12, 0xed, 0x45,
	0x89, 0x8f, 0x49, 0xca, 0xad, 0x11, 0xd7, 0x24, 0xfd, 0xd4, 0xc8, 0x44, 0x3e, 0x83, 0xae, 0x8f,
	0x22, 0xf4, 0x52, 0x5c, 0x46, 0x13, 0x3f, 0xd0, 0x41, 0x34, 0xe1, 0x15, 0xa2, 0x99, 0xf1, 0x5c,
	0x63, 0x1d, 0xe7, 0x0e, 0xdb, 0x83, 0xd6, 0xb9, 0x50, 0x98, 0x45, 0xab, 0xe0, 0x06, 0x79, 0xb5,
	0x67, 0xf5, 0x2d, 0xa7, 0x61, 0x64, 0x4a, 0x76, 0x83, 0x1b, 0x64, 0xfb, 0xd0, 0x51, 0xe2, 0x02,
	0xf5, 0xbc, 0x48, 0xd6, 0x88, 0x6c, 0xa5, 0xc6, 0x82, 0x3d, 0x84, 0xee, 0x58, 0x5c, 0x7b, 0x19,
	0xaf, 0x13, 0xe1, 0xa3, 0x27, 0xa4, 0xe4, 0xeb, 0x34, 0x45, 0x67, 0x2c, 0xae, 0x5d, 0xb2, 0x46,
	0xc6, 0x39, 0x92, 0x92, 0xed, 0x42, 0x33, 0x4e, 0x02, 0x89, 0x9e, 0x8f, 0x33, 0x41, 0x03, 0x03,
	0xa1, 0x0d, 0x52, 0x87, 0x99, 0xc8, 0x5e, 0xc1, 0x56, 0x69, 0x86, 0x59, 0x14, 0x4e, 0xc7, 0xe8,
	0x29, 0x29, 0x42, 0xe4, 0x75, 0xea, 0xf8, 0xb7, 0x30, 0xcb, 0x67, 0xb2, 0x5d, 0xe3, 0xb2, 0x97,
	0xb0, 0x59, 0x1e, 0x5f, 0x63, 0x9c, 0x35, 0x6e, 0x50, 0x63, 0xb7, 0x78, 0x08, 0x8d, 0x71, 0xda,
	0xf6, 0x08, 0xea, 0x5a, 0x5c, 0xa1, 0x17, 0x27, 0xd1, 0x45, 0xa0, 0x79, 0x83, 0x50, 0x30, 0xd2,
	0x19, 0x29, 0xe6, 0xfb, 0x69, 0x91, 0x5c, 0xa2, 0xce, 0x91, 0x66, 0xfa, 0xfd, 0x52, 0x31, 0x83,
	0x5e, 0xc3, 0xb6, 0x08, 0xc3, 0x48, 0x0a, 0x8d, 0xde, 0xc5, 0x74, 0xe2, 0x2b, 0x4f, 0x47, 0x5e,
	0xfe, 0x85, 0x79, 0x8b, 0x3a, 0x36, 0x73, 0xe2, 0xad, 0x01, 0x46, 0xd1, 0xed, 0x0e, 0x6e, 0x42,
	0x75, 0xaa, 0x30, 0xf1, 0x02, 0x9f, 0xb7, 0x89, 0xac, 0x98, 0xf2, 0x9d, 0xcf, 0x38, 0x54, 0x67,
	0x98, 0x28, 0xf3, 0xd7, 0xea, 0xf4, 0xac, 0xfe, 0xaa, 0x93, 0x97, 0xec, 0x39, 0x54, 0x94, 0x16,
	0x7a, 0xaa, 0x38, 0xeb, 0x59, 0xfd, 0xe6, 0x60, 0xeb, 0xe0, 0x76, 0xdd, 0xdd, 0xc5, 0x83, 0x01,
	0x9c, 0x0c, 0x64, 0xbb, 0xb0, 0xa6, 0x74, 0x24, 0xaf, 0xf8, 0x3f, 0xbd, 0xd5, 0x7e, 0x7d, 0xd0,
	0x2a, 0x76, 0x44, 0xf2, 0xca, 0x49, 0x5d, 0xdb, 0x86, 0x4a, 0xda, 0xc8, 0xea, 0x50, 0x75, 0x47,
	0xa7, 0x67, 0x67, 0x27, 0xc3, 0xf6, 0x5f, 0x69, 0x71, 0xe4, 0x8c, 0x4e, 0x86, 0x6d, 0xcb, 0xde,
	0x83, 0x35, 0xea, 0x61, 0xff, 0x03, 0x50, 0x57, 0x7a, 0x55, 0xd2, 0x5b, 0xb4, 0x4e, 0x8a, 0xb9,
	0x27, 0xf6, 0x31, 0x74, 0x8e, 0x13, 0x14, 0x1a, 0xf3, 0x99, 0x1c, 0xfc, 0xce, 0x0e, 0xe0, 0xf6,
	0x2a, 0x52, 0x47, 0x7d, 0xc0, 0x96, 0x87, 0x77, 0x16, 0xd7, 0xf5, 0x17, 0x21, 0xea, 0x4f, 0x42,
	0x3e, 0xc5, 0xfe, 0xf2, 0x24, 0xee, 0x6f, 0x84, 0xb8, 0xf7, 0x84, 0xa8, 0x07, 0x87, 0x3c, 0x86,
	0x96, 0x83, 0xc2, 0x2f, 0xce, 0x71, 0xe7, 0x7f, 0x90, 0x7d, 0x74, 0x17, 0x79, 0xf8, 0x5b, 0x76,
	0xa0, 0x33, 0xc4, 0x10, 0xcb, 0xe7, 0xbd, 0xfb, 0x9e, 0xa7, 0xcb, 0x90, 0x32, 0x3b, 0xa7, 0xa6,
	0x52, 0xa2, 0x52, 0x44, 0xd6, 0x9c, 0xbc, 0xb4, 0xf7, 0xa1, 0xf5, 0x21, 0x50, 0xba, 0x98, 0x58,
	0xd8, 0x5c, 0xab, 0xb8, 0xb9, 0xe6, 0x08, 0x65, 0xf6, 0xc1, 0x47, 0x18, 0x7c, 0x85, 0x56, 0xfe,
	0xec, 0x62, 0x32, 0x0b, 0x24, 0xb2, 0xf7, 0xd0, 0x2c, 0xaf, 0x02, 0xfb, 0x6f, 0x11, 0xb1, 0xb4,
	0x69, 0xdb, 0xf7, 0x98, 0xea, 0xcd, 0xc6, 0x17, 0xc8, 0xdd, 0xf8, 0xfc, 0xbc, 0x42, 0x3f, 0x12,
	0x2f, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0x70, 0xec, 0x0c, 0xa6, 0x3c, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StrategyServiceClient is the client API for StrategyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StrategyServiceClient interface {
	CreateStrategy(ctx context.Context, in *CreateStrategyReq, opts ...grpc.CallOption) (*CreateStrategyRes, error)
}

type strategyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStrategyServiceClient(cc grpc.ClientConnInterface) StrategyServiceClient {
	return &strategyServiceClient{cc}
}

func (c *strategyServiceClient) CreateStrategy(ctx context.Context, in *CreateStrategyReq, opts ...grpc.CallOption) (*CreateStrategyRes, error) {
	out := new(CreateStrategyRes)
	err := c.cc.Invoke(ctx, "/strategy.StrategyService/CreateStrategy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StrategyServiceServer is the server API for StrategyService service.
type StrategyServiceServer interface {
	CreateStrategy(context.Context, *CreateStrategyReq) (*CreateStrategyRes, error)
}

// UnimplementedStrategyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStrategyServiceServer struct {
}

func (*UnimplementedStrategyServiceServer) CreateStrategy(ctx context.Context, req *CreateStrategyReq) (*CreateStrategyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStrategy not implemented")
}

func RegisterStrategyServiceServer(s *grpc.Server, srv StrategyServiceServer) {
	s.RegisterService(&_StrategyService_serviceDesc, srv)
}

func _StrategyService_CreateStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStrategyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServiceServer).CreateStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/strategy.StrategyService/CreateStrategy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServiceServer).CreateStrategy(ctx, req.(*CreateStrategyReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _StrategyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "strategy.StrategyService",
	HandlerType: (*StrategyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStrategy",
			Handler:    _StrategyService_CreateStrategy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/strategy.proto",
}
