---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-service-app
  namespace: hedgina
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-service
  template:
    metadata:
      labels:
        app: price-service
    spec:
      containers:
      - name: price-service
        image: neha190495/price-service:latest
        imagePullPolicy: IfNotPresent
        resources: {}
        ports:
        - containerPort: 50053
---
apiVersion: v1
kind: Service
metadata:
  name: price-service
  namespace: hedgina
spec:
  type: LoadBalancer
  ports:
  - name: tcp
    port: 50053
    protocol: TCP
    targetPort: 50053
  selector:
    app: price-service