---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cep-rule-service-app
  namespace: hedgina
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cep-rule-service
  template:
    metadata:
      labels:
        app: cep-rule-service
    spec:
      containers:
      - name: cep-rule-service
        image: neha190495/cep-rule-service:latest
        imagePullPolicy: Always
        resources: {}
        ports:
        - containerPort: 50056
---
apiVersion: v1
kind: Service
metadata:
  name: cep-rule-service
  namespace: hedgina
spec:
  type: LoadBalancer
  ports:
  - name: tcp
    port: 50056
    protocol: TCP
    targetPort: 50056
  selector:
    app: cep-rule-service