// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/eventhistory.proto

package eventhistorypb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListEventHistoryReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEventHistoryReq) Reset()         { *m = ListEventHistoryReq{} }
func (m *ListEventHistoryReq) String() string { return proto.CompactTextString(m) }
func (*ListEventHistoryReq) ProtoMessage()    {}
func (*ListEventHistoryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bf2a04f2257c1f, []int{0}
}

func (m *ListEventHistoryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventHistoryReq.Unmarshal(m, b)
}
func (m *ListEventHistoryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventHistoryReq.Marshal(b, m, deterministic)
}
func (m *ListEventHistoryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventHistoryReq.Merge(m, src)
}
func (m *ListEventHistoryReq) XXX_Size() int {
	return xxx_messageInfo_ListEventHistoryReq.Size(m)
}
func (m *ListEventHistoryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventHistoryReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventHistoryReq proto.InternalMessageInfo

func (m *ListEventHistoryReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ListEventHistoryRes struct {
	EventHistoryExchange *EventHistoryExchange `protobuf:"bytes,1,opt,name=eventHistoryExchange,proto3" json:"eventHistoryExchange,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListEventHistoryRes) Reset()         { *m = ListEventHistoryRes{} }
func (m *ListEventHistoryRes) String() string { return proto.CompactTextString(m) }
func (*ListEventHistoryRes) ProtoMessage()    {}
func (*ListEventHistoryRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bf2a04f2257c1f, []int{1}
}

func (m *ListEventHistoryRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventHistoryRes.Unmarshal(m, b)
}
func (m *ListEventHistoryRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventHistoryRes.Marshal(b, m, deterministic)
}
func (m *ListEventHistoryRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventHistoryRes.Merge(m, src)
}
func (m *ListEventHistoryRes) XXX_Size() int {
	return xxx_messageInfo_ListEventHistoryRes.Size(m)
}
func (m *ListEventHistoryRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventHistoryRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventHistoryRes proto.InternalMessageInfo

func (m *ListEventHistoryRes) GetEventHistoryExchange() *EventHistoryExchange {
	if m != nil {
		return m.EventHistoryExchange
	}
	return nil
}

type EventHistoryExchange struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OperationType        string    `protobuf:"bytes,2,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	Timestamp            string    `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Db                   string    `protobuf:"bytes,4,opt,name=db,proto3" json:"db,omitempty"`
	Collection           string    `protobuf:"bytes,5,opt,name=collection,proto3" json:"collection,omitempty"`
	Name                 string    `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	UserId               string    `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExchangeId           string    `protobuf:"bytes,8,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	OldValue             *Exchange `protobuf:"bytes,9,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue             *Exchange `protobuf:"bytes,10,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EventHistoryExchange) Reset()         { *m = EventHistoryExchange{} }
func (m *EventHistoryExchange) String() string { return proto.CompactTextString(m) }
func (*EventHistoryExchange) ProtoMessage()    {}
func (*EventHistoryExchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bf2a04f2257c1f, []int{2}
}

func (m *EventHistoryExchange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventHistoryExchange.Unmarshal(m, b)
}
func (m *EventHistoryExchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventHistoryExchange.Marshal(b, m, deterministic)
}
func (m *EventHistoryExchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventHistoryExchange.Merge(m, src)
}
func (m *EventHistoryExchange) XXX_Size() int {
	return xxx_messageInfo_EventHistoryExchange.Size(m)
}
func (m *EventHistoryExchange) XXX_DiscardUnknown() {
	xxx_messageInfo_EventHistoryExchange.DiscardUnknown(m)
}

var xxx_messageInfo_EventHistoryExchange proto.InternalMessageInfo

func (m *EventHistoryExchange) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EventHistoryExchange) GetOperationType() string {
	if m != nil {
		return m.OperationType
	}
	return ""
}

func (m *EventHistoryExchange) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *EventHistoryExchange) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *EventHistoryExchange) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

func (m *EventHistoryExchange) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EventHistoryExchange) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *EventHistoryExchange) GetExchangeId() string {
	if m != nil {
		return m.ExchangeId
	}
	return ""
}

func (m *EventHistoryExchange) GetOldValue() *Exchange {
	if m != nil {
		return m.OldValue
	}
	return nil
}

func (m *EventHistoryExchange) GetNewValue() *Exchange {
	if m != nil {
		return m.NewValue
	}
	return nil
}

type Exchange struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SelectedExchange     string   `protobuf:"bytes,2,opt,name=selected_exchange,json=selectedExchange,proto3" json:"selected_exchange,omitempty"`
	ExchangeName         string   `protobuf:"bytes,3,opt,name=exchange_name,json=exchangeName,proto3" json:"exchange_name,omitempty"`
	ExchangeType         string   `protobuf:"bytes,4,opt,name=exchange_type,json=exchangeType,proto3" json:"exchange_type,omitempty"`
	UserId               string   `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApiKey               string   `protobuf:"bytes,6,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ApiSecret            string   `protobuf:"bytes,7,opt,name=api_secret,json=apiSecret,proto3" json:"api_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Exchange) Reset()         { *m = Exchange{} }
func (m *Exchange) String() string { return proto.CompactTextString(m) }
func (*Exchange) ProtoMessage()    {}
func (*Exchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bf2a04f2257c1f, []int{3}
}

func (m *Exchange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exchange.Unmarshal(m, b)
}
func (m *Exchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exchange.Marshal(b, m, deterministic)
}
func (m *Exchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exchange.Merge(m, src)
}
func (m *Exchange) XXX_Size() int {
	return xxx_messageInfo_Exchange.Size(m)
}
func (m *Exchange) XXX_DiscardUnknown() {
	xxx_messageInfo_Exchange.DiscardUnknown(m)
}

var xxx_messageInfo_Exchange proto.InternalMessageInfo

func (m *Exchange) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Exchange) GetSelectedExchange() string {
	if m != nil {
		return m.SelectedExchange
	}
	return ""
}

func (m *Exchange) GetExchangeName() string {
	if m != nil {
		return m.ExchangeName
	}
	return ""
}

func (m *Exchange) GetExchangeType() string {
	if m != nil {
		return m.ExchangeType
	}
	return ""
}

func (m *Exchange) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Exchange) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *Exchange) GetApiSecret() string {
	if m != nil {
		return m.ApiSecret
	}
	return ""
}

func init() {
	proto.RegisterType((*ListEventHistoryReq)(nil), "eventhistory.ListEventHistoryReq")
	proto.RegisterType((*ListEventHistoryRes)(nil), "eventhistory.ListEventHistoryRes")
	proto.RegisterType((*EventHistoryExchange)(nil), "eventhistory.EventHistoryExchange")
	proto.RegisterType((*Exchange)(nil), "eventhistory.Exchange")
}

func init() {
	proto.RegisterFile("proto/eventhistory.proto", fileDescriptor_07bf2a04f2257c1f)
}

var fileDescriptor_07bf2a04f2257c1f = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xed, 0x6a, 0xd5, 0x30,
	0x18, 0xc7, 0x69, 0x3d, 0xeb, 0x39, 0x7d, 0xb6, 0x1d, 0x8e, 0xd9, 0x70, 0x41, 0x7c, 0xad, 0x08,
	0x82, 0x70, 0x94, 0xed, 0x0e, 0x84, 0x03, 0x0e, 0xc5, 0x0f, 0x67, 0xb2, 0x0f, 0xfb, 0x52, 0xd2,
	0xe6, 0xc1, 0x05, 0xdb, 0x26, 0x6b, 0xb2, 0x33, 0x7b, 0x9d, 0xde, 0x81, 0x57, 0x22, 0x49, 0x5f,
	0x4c, 0x47, 0xd5, 0x6f, 0xed, 0xff, 0x25, 0x3c, 0xf9, 0x25, 0x01, 0xaa, 0x6a, 0x69, 0xe4, 0x3b,
	0xdc, 0x61, 0x65, 0xae, 0x85, 0x36, 0xb2, 0x6e, 0xd6, 0x4e, 0x22, 0x07, 0xbe, 0x96, 0xac, 0xe1,
	0xe8, 0xb3, 0xd0, 0x66, 0x63, 0xb5, 0x8f, 0xad, 0xb6, 0xc5, 0x1b, 0x72, 0x02, 0xf3, 0x5b, 0x8d,
	0x75, 0x2a, 0x38, 0x0d, 0x5e, 0x04, 0x6f, 0xe2, 0x6d, 0x64, 0x7f, 0xcf, 0x79, 0x52, 0x4e, 0xe5,
	0x35, 0xb9, 0x84, 0x63, 0xf4, 0xa4, 0xcd, 0x8f, 0xfc, 0x9a, 0x55, 0xdf, 0xd0, 0x95, 0xf7, 0x4f,
	0x93, 0xf5, 0x68, 0x8e, 0xcd, 0x44, 0x72, 0x3b, 0xd9, 0x4f, 0x7e, 0x86, 0x70, 0x3c, 0x15, 0x27,
	0x4b, 0x08, 0x87, 0xd9, 0x42, 0xc1, 0xc9, 0x6b, 0x58, 0x4a, 0x85, 0x35, 0x33, 0x42, 0x56, 0xa9,
	0x69, 0x14, 0xd2, 0xd0, 0x79, 0x87, 0x83, 0xfa, 0xb5, 0x51, 0x48, 0x9e, 0x40, 0x6c, 0x44, 0x89,
	0xda, 0xb0, 0x52, 0xd1, 0x07, 0x2e, 0xf1, 0x47, 0xb0, 0x8b, 0xf2, 0x8c, 0xce, 0xda, 0x45, 0x79,
	0x46, 0x9e, 0x01, 0xe4, 0xb2, 0x28, 0x30, 0xb7, 0x7d, 0xba, 0xe7, 0x74, 0x4f, 0x21, 0x04, 0x66,
	0x15, 0x2b, 0x91, 0x46, 0xce, 0x71, 0xdf, 0x3e, 0xb9, 0xb9, 0x4f, 0x8e, 0x3c, 0x87, 0x7d, 0xec,
	0xa6, 0xb7, 0xe6, 0xa2, 0x5d, 0xad, 0x97, 0xce, 0x39, 0x39, 0x83, 0x58, 0x16, 0x3c, 0xdd, 0xb1,
	0xe2, 0x16, 0x69, 0xec, 0xc0, 0x3d, 0xba, 0x07, 0xae, 0x87, 0xb5, 0x90, 0x05, 0xbf, 0xb4, 0x39,
	0x5b, 0xaa, 0xf0, 0xae, 0x2b, 0xc1, 0xbf, 0x4b, 0x15, 0xde, 0xb9, 0x52, 0xf2, 0x2b, 0x80, 0xc5,
	0x5f, 0x49, 0xbe, 0x85, 0x87, 0x1a, 0xed, 0x0e, 0x91, 0xa7, 0xfd, 0x74, 0x1d, 0xcc, 0x55, 0x6f,
	0x0c, 0xe5, 0x57, 0x70, 0x38, 0x6c, 0xca, 0xa1, 0x68, 0x99, 0x1e, 0xf4, 0xe2, 0x17, 0x8b, 0xc4,
	0x0f, 0xb9, 0xa3, 0x99, 0x8d, 0x43, 0xee, 0x64, 0x3c, 0x6e, 0x7b, 0x23, 0x6e, 0x27, 0x30, 0x67,
	0x4a, 0xa4, 0xdf, 0xb1, 0xe9, 0x38, 0x47, 0x4c, 0x89, 0x4f, 0xd8, 0x90, 0xa7, 0x00, 0xd6, 0xd0,
	0x98, 0xd7, 0x68, 0x3a, 0xd8, 0x31, 0x53, 0xe2, 0xc2, 0x09, 0xa7, 0x37, 0x70, 0xe4, 0xdf, 0x9c,
	0x0b, 0xac, 0x77, 0x22, 0x47, 0x72, 0x05, 0xab, 0xfb, 0x17, 0x98, 0xbc, 0x1c, 0x13, 0x9b, 0x78,
	0x10, 0x8f, 0xff, 0x1b, 0xd1, 0xef, 0x83, 0x0f, 0xab, 0xab, 0xa5, 0x9f, 0x52, 0x59, 0x16, 0xb9,
	0x37, 0x77, 0xf6, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x36, 0xf5, 0x9a, 0xde, 0x8f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EventHistoryServiceClient is the client API for EventHistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventHistoryServiceClient interface {
	ListEventHistory(ctx context.Context, in *ListEventHistoryReq, opts ...grpc.CallOption) (EventHistoryService_ListEventHistoryClient, error)
}

type eventHistoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventHistoryServiceClient(cc grpc.ClientConnInterface) EventHistoryServiceClient {
	return &eventHistoryServiceClient{cc}
}

func (c *eventHistoryServiceClient) ListEventHistory(ctx context.Context, in *ListEventHistoryReq, opts ...grpc.CallOption) (EventHistoryService_ListEventHistoryClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EventHistoryService_serviceDesc.Streams[0], "/eventhistory.EventHistoryService/ListEventHistory", opts...)
	if err != nil {
		return nil, err
	}
	x := &eventHistoryServiceListEventHistoryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EventHistoryService_ListEventHistoryClient interface {
	Recv() (*ListEventHistoryRes, error)
	grpc.ClientStream
}

type eventHistoryServiceListEventHistoryClient struct {
	grpc.ClientStream
}

func (x *eventHistoryServiceListEventHistoryClient) Recv() (*ListEventHistoryRes, error) {
	m := new(ListEventHistoryRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EventHistoryServiceServer is the server API for EventHistoryService service.
type EventHistoryServiceServer interface {
	ListEventHistory(*ListEventHistoryReq, EventHistoryService_ListEventHistoryServer) error
}

// UnimplementedEventHistoryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEventHistoryServiceServer struct {
}

func (*UnimplementedEventHistoryServiceServer) ListEventHistory(req *ListEventHistoryReq, srv EventHistoryService_ListEventHistoryServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEventHistory not implemented")
}

func RegisterEventHistoryServiceServer(s *grpc.Server, srv EventHistoryServiceServer) {
	s.RegisterService(&_EventHistoryService_serviceDesc, srv)
}

func _EventHistoryService_ListEventHistory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEventHistoryReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventHistoryServiceServer).ListEventHistory(m, &eventHistoryServiceListEventHistoryServer{stream})
}

type EventHistoryService_ListEventHistoryServer interface {
	Send(*ListEventHistoryRes) error
	grpc.ServerStream
}

type eventHistoryServiceListEventHistoryServer struct {
	grpc.ServerStream
}

func (x *eventHistoryServiceListEventHistoryServer) Send(m *ListEventHistoryRes) error {
	return x.ServerStream.SendMsg(m)
}

var _EventHistoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eventhistory.EventHistoryService",
	HandlerType: (*EventHistoryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEventHistory",
			Handler:       _EventHistoryService_ListEventHistory_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/eventhistory.proto",
}
